const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const faults={
 lamp:{name:'Red lamp open circuit',electrical:'Measure voltage at the red-lamp terminals. Supply may be present while continuity through the lamp is open.',safety:'Secure the approach and place the intersection in all-red/manual control before opening the signal head.',cyber:'Controller command and identity are valid; compare commanded state with physical feedback.',action:'repair'},
 conflict:{name:'Conflicting green signals',electrical:'Verify output voltages independently; do not assume the display reflects the physical outputs.',safety:'This is immediately dangerous. Force all-red, close the junction and authorise restart only after verification.',cyber:'Check controller interlocks, command signatures and the event sequence for an unauthorised phase.',action:'allred'},
 sensor:{name:'Vehicle sensor failure',electrical:'Check loop-sensor supply, resistance and input switching at the controller.',safety:'Use a controlled fixed-time plan while the detector is unavailable.',cyber:'Compare sensor identity, heartbeat and packet timestamps before replacing hardware.',action:'repair'},
 button:{name:'Pedestrian button failure',electrical:'Test continuity and the 24 V input transition while the button is pressed.',safety:'Provide a protected manual crossing arrangement until demand detection is restored.',cyber:'Verify that the button CyberTwin is authenticated and messages reach the edge node.',action:'repair'},
 timing:{name:'Controller timing fault',electrical:'Supply and lamps are normal; measure the actual phase durations against the configured values.',safety:'Select a safe approved fallback plan and prevent unsafe short clearance periods.',cyber:'Inspect configuration provenance and reject unapproved timing changes.',action:'allred'},
 cable:{name:'Signal cable disconnection',electrical:'Isolate the circuit, then perform continuity and insulation checks on the affected cable.',safety:'Secure the dark approach and maintain all-red or supervised control.',cyber:'Physical feedback is missing although controller identity remains valid.',action:'repair'},
 short:{name:'Output short circuit',electrical:'Isolate supply, verify protective-device operation and locate the low-resistance path.',safety:'Do not repeatedly reset protection. Maintain the junction in a safe controlled state.',cyber:'Use current and trip-event provenance to distinguish a wiring fault from a false command.',action:'repair'},
 cyber:{name:'Unauthorised phase command',electrical:'Physical wiring may be healthy. Compare output voltage with the authorised command schedule.',safety:'Force all-red and block remote phase changes until trusted control is restored.',cyber:'Quarantine the unsigned command, rotate credentials and verify the trusted controller image.',action:'allred'},
 drop:{name:'Supply voltage drop',electrical:'Measure the 24 V supply under load and calculate cable/connection voltage drop.',safety:'Do not operate unreliable signal heads; use a safe fallback until voltage is stable.',cyber:'Power-quality evidence is consistent across trusted sensors, suggesting a physical supply issue.',action:'repair'}
};
let state={fault:null,mode:'mystery',start:Date.now(),packets:0,consulted:new Set(),events:[],phase:'allred',running:false,score:null};
function log(msg,type='INFO'){const e={time:new Date().toISOString(),type,msg};state.events.push(e);state.packets++;$('#packetCount').textContent=state.packets;const p=document.createElement('p');p.textContent=`${e.time.slice(11,19)} [${type}] ${msg}`;$('#eventLog').prepend(p)}
function resetConsults(){state.consulted.clear();$$('.reply').forEach(x=>{x.classList.add('hidden');x.textContent=''});$$('[data-agent]').forEach(x=>x.disabled=false);$('#coordinated').className='feedback neutral';$('#coordinated').textContent='The coordinated recommendation unlocks after all three consultations.'}
function applyFault(key,mode='instructor'){state.fault=key;state.mode=mode;state.start=Date.now();state.score=null;resetConsults();$('#modeBadge').textContent=mode==='mystery'?'MYSTERY MODE':'INSTRUCTOR MODE';$('#missionCode').textContent='Mission EL-'+Math.floor(100+Math.random()*900);$('#scoreBadge').textContent='Score: —';$('#result').className='feedback neutral';$('#result').textContent='Complete the investigation before submission.';setSignals('allred');$('#certificate').textContent=key==='cyber'?'WARNING':'VALID';$('#controllerTrust').textContent=key==='cyber'?'UNTRUSTED CMD':'TRUSTED';$('#trafficVoltage').textContent=key==='drop'?'17.8 V':'24.0 V';$('#supplyDisplay').textContent=key==='drop'?'17.8 V DC':'24.0 V DC';$('#vehicleSensor').textContent=key==='sensor'?'NO HEARTBEAT':'CLEAR';log(`${mode==='mystery'?'Hidden scenario':'Instructor fault'} activated`,'SCENARIO');if(key==='conflict'||key==='cyber')setTimeout(()=>setSignals('conflict'),900);if(key==='lamp')setTimeout(()=>{$('.north .red').classList.remove('on');log('Red command active; north red lamp feedback absent','ALARM')},700)}
function setSignals(phase){state.phase=phase;$$('.traffic i').forEach(x=>x.classList.remove('on'));const redAll=()=>$$('.traffic .red').forEach(x=>x.classList.add('on'));if(phase==='allred'){redAll();$('#safeOverlay').classList.add('show');$('#phase').textContent='ALL RED'}else if(phase==='ns'){$$('.north .green,.south .green,.east .red,.west .red').forEach(x=>x.classList.add('on'));$('#safeOverlay').classList.remove('show');$('#phase').textContent='N–S GREEN'}else if(phase==='ew'){$$('.east .green,.west .green,.north .red,.south .red').forEach(x=>x.classList.add('on'));$('#safeOverlay').classList.remove('show');$('#phase').textContent='E–W GREEN'}else if(phase==='conflict'){$$('.north .green,.east .green,.south .red,.west .red').forEach(x=>x.classList.add('on'));$('#safeOverlay').classList.remove('show');$('#phase').textContent='CONFLICT';log('Conflicting green outputs detected','CRITICAL')}}
function trafficCycle(){if(!state.running)return;if(state.fault==='conflict'||state.fault==='cyber'){setSignals('conflict');return}setSignals(state.phase==='ns'?'ew':'ns');setTimeout(trafficCycle,state.fault==='timing'?1800:4500)}
$('#startTraffic').onclick=()=>{state.running=!state.running;$('#startTraffic').textContent=state.running?'Pause Sequence':'Run Sequence';if(state.running){setSignals('ns');log('Traffic sequence started');setTimeout(trafficCycle,4500)}};
$('#safeState').onclick=()=>{state.running=false;$('#startTraffic').textContent='Run Sequence';setSignals('allred');log('Human operator forced all-red safe state','SAFETY')};
$('#pedButton').onclick=$('#requestCrossing').onclick=()=>{log(state.fault==='button'?'Pedestrian request not received':'Pedestrian request registered',state.fault==='button'?'FAULT':'INPUT')};
$('#injectFault').onclick=()=>applyFault($('#faultSelect').value,'instructor');$('#normalMode').onclick=()=>{state.fault=null;resetConsults();setSignals('allred');$('#trafficVoltage').textContent='24.0 V';$('#controllerTrust').textContent='TRUSTED';$('#certificate').textContent='VALID';log('System restored to normal')};
$('#newMission').onclick=()=>{const keys=Object.keys(faults);applyFault(keys[Math.floor(Math.random()*keys.length)],'mystery')};
$('#takeMeasurement').onclick=()=>{const fn=$('#functionSelect').value,conn=$('#connection').value,inst=$('#instrument').value,range=$('#rangeSelect').value;let ok=false,val='OL';if(fn==='vdc'&&conn==='parallel'&&inst!=='ammeter'){ok=true;val=(state.fault==='drop'?17.8:24).toFixed(1)+' V'}else if(fn==='adc'&&conn==='series'&&(inst==='ammeter'||inst==='multimeter')){ok=true;val=(state.fault==='short'?'>2.0':state.fault==='cable'||state.fault==='lamp'?'0.00':'0.50')+' A'}else if(fn==='resistance'&&conn==='parallel'&&state.fault==='lamp'){ok=true;val='OL Ω'}if(range==='2'&&fn==='vdc'){ok=false;val='OL'}if(conn==='wrong'){ok=false;val='FUSE'}$('#meterDisplay').textContent=val;$('#measurementFeedback').className='feedback '+(ok?'success':'error');$('#measurementFeedback').textContent=ok?`Valid measurement recorded: ${val}. Compare it with the controller command and expected circuit value.`:'Unsafe or invalid test configuration. Recheck instrument, function, range, probe port and series/parallel connection.';log(`Measurement ${val}; function=${fn}; connection=${conn}; accepted=${ok}`,ok?'MEASURE':'TEST ERROR')};
$$('[data-agent]').forEach(b=>b.onclick=()=>{if(!state.fault){alert('Start a fault scenario first.');return}const a=b.dataset.agent;state.consulted.add(a);const box=$('#'+a+'Reply');box.textContent=faults[state.fault][a];box.classList.remove('hidden');b.disabled=true;log(`${b.closest('article').querySelector('h3').textContent} consulted`,'AGENT');if(state.consulted.size===3){$('#coordinated').className='feedback success';$('#coordinated').textContent='Coordinated recommendation: establish a verified safe state, validate electrical measurements against trusted controller evidence, repair or quarantine the cause, then perform an independent functional test before restart.'}});
$('#submitDecision').onclick=()=>{if(!state.fault)return;const diagnosis=$('#diagnosis').value,action=$('#action').value,text=$('#justification').value.trim();let s=0;if(diagnosis===state.fault)s+=40;if(action===faults[state.fault].action)s+=25;if(state.consulted.size===3)s+=20;if(text.length>=45)s+=15;state.score=s;$('#scoreBadge').textContent='Score: '+s+'/100';$('#result').className='feedback '+(s>=75?'success':s>=50?'warning':'error');$('#result').textContent=`${s>=75?'Competent decision':'Decision requires review'}. Actual condition: ${faults[state.fault].name}. Score ${s}/100.`;log(`Human decision submitted; diagnosis=${diagnosis}; action=${action}; score=${s}`,'DECISION')};
$('#exportJson').onclick=()=>{const out={schema:'tvet-cybertwin-evidence/v1',exportedAt:new Date().toISOString(),mission:$('#missionCode').textContent,cybertwin:{id:$('#assetId').textContent,edge:'EDGE-LAB-01',certificate:$('#certificate').textContent},mode:state.mode,fault:state.fault?faults[state.fault].name:null,consultedAgents:[...state.consulted],learner:{diagnosis:$('#diagnosis').value,action:$('#action').value,justification:$('#justification').value,score:state.score},events:state.events};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download=`${$('#missionCode').textContent}-cybertwin-evidence.json`;a.click();URL.revokeObjectURL(a.href);log('Owner exported CyberTwin evidence JSON','EXPORT')};
setInterval(()=>{$('#timer').textContent=new Date(Date.now()-state.start).toISOString().slice(14,19)},1000);applyFault('lamp','mystery');
